version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
      args:
        NODE_ENV: $NODE_ENV
        PORT: $API_SERVICE_PORT
    restart: always
    ports:
      - "$API_SERVICE_PORT:$API_SERVICE_PORT"
    volumes:
      - ./api-server:/usr/src/app # has to be the same as in WORKDIR in Dockerfile
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $API_SERVICE_PORT
      CACHE_HOST: redis
      CACHE_PORT: 6379
      DB_DATABASE: $DB_NAME
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_PORT: 5432
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - api-server

volumes:
  postgres_data:
